{
  "build": {
    "builder": "nixpacks",
    "buildCommand": "npm install && npx prisma generate && tsc"
  },
  "deploy": {
    "startCommand": "npm start",
    "healthcheckPath": "/",
    "healthcheckTimeout": 100
  }
}